### ISSUE TITLE
kleiner Fehler im Installationskript

### ISSUE THREAD

**Issue by machschev** [Tronde/Raspi-SHT21#36]
Wenn ich setup.py per sudo aufrufe bekomme ich folgende Fehlermeldung:

```
Place files in webroot
cp: der Aufruf von stat für 'www/*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
```
im richtigen Verzeichnis habe ich nun nachträglich

`sudo cp -rpv www/* /var/www/html`

ausgeführt und schon sind die Dateien wo sie hingehören.
Danke für das tolle Skript!

**Comment by Tronde** [comment]
Hast du das Skript `setup.sh` mit `sudo` ausgeführt? und befandest du dich dabei in gleichen Verzeichnis, in dem sich das Verzeichnis _www_ befindet?

Die Fehlermeldung deutet darauf hin, dass die Quelle `www/*` nicht gelesen werden konnte. Ich kann diesen Fehler bei mir jedoch nicht nachstellen.

Kannst du mir ggf. einmal genau beschreiben wie der Verzeichnisinhalt bei dir nach entpacken Archivs bzw. klonen des Repos aussieht und wie du dann das Skript aufrufst? Dann kann ich versuchen den Fehler nachzustellen.

**Comment by machschev** [comment]
ja das Skript habe ich mit sudo in dem Verzeichnis aufgerufen in dem es liegt. Ich denke das ist erstmal der logische Weg. Es fehlt für cp www/* einfach der komplette Pfad im Skript, dann wäre es egal von wo das Skript aufgerufen wird.

**Comment by Tronde** [comment]
Der Ordner www sollte parallel zum Setup-Skript liegen und stets über die relative Pfadangabe gefunden werden.

Es ist mir leider noch nicht gelungen, das Problem nachzustellen.

**Comment by machschev** [comment]
also normalerweise macht sudo auch einen $PATH Reset, das heisst er läuft nicht mehr vom Verzeichnis los in dem setup.sh liegt. Das könnte auf unterschiedlichen Systemen unterschiedlich konfiguriert sein.
```
pi@tempi:~ $ echo $PATH
/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
pi@tempi:~ $ sudo -i
root@tempi:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Daher wäre es besser den kompletten Pfad ins Skript zu übernehmen.

**Comment by Tronde** [comment]
Hast du denn den Pfad, in dem sich das Installationsskript befindet, deinem PATH hinzugefügt? Das Verzeichnis, in dem sich das Skript `setup.py` befindet gehört normalerweise nicht zum Umfang von PATH.

Das Problem mit dem absoluten Pfad ist, dass dieser auf jedem System anders sein kann. Diesen erst per Hand im Installationsskript eintragen zu müssen, finde ich nicht so elegant. Alternativ könnte man den Pfad evtl. durch das Setupskript ermitteln lassen.

Bevor ich an dieser Stelle eine Änderung vornehme, möchte ich das erst einige Male testen, um zu sehen, welche Variante weniger Probleme bereitet.

**Comment by machschev** [comment]
Ich denke der Weg der normalerweise genommen wird ist im Verzeichnis in dem setup.sh liegt mit 
`# sudo ./setup.sh`
aufzurufen
Dann würde es helfen wenn du einfach ./www/* nehmen würdest. Das sollte klappen.

**Comment by Tronde** [comment]
Hallo,
ich habe den Vorschlag aus [diesem Beitrag](https://github.com/Tronde/Raspi-SHT21/issues/36#issuecomment-370333979) in das Skript `setup.sh` eingebaut. Die gepatchte Version kann getestet werden, in dem der [Dev-Branch](https://github.com/Tronde/Raspi-SHT21/tree/v2.x.x-dev) genutzt wird.

Ich freue mich, wenn dies jemand testen kann und mir hier eine Rückmeldung gibt. Da ich das Problem an sich nicht reproduzieren kann, kann ich nicht ausschließen, dass dieser Fix die Situation verschlimmbessert.

Gruß
Tronde
